Fixing rekeyTo makeTxnWithSuggestedParams bug
algorand/js-algorand-sdk pull request #267
Opened 2021-01-15 20:33 UTC by Alex99y

The current implementation of these functions initializes the object with the field rekeyTo  (lowercase letter K) causing the build of the rekey transaction to fail because the expected field name is reKeyTo (uppercase letter K).

- makePaymentTxnWithSuggestedParams
- makeKeyRegistrationTxnWithSuggestedParams
- makeAssetCreateTxnWithSuggestedParams
- makeAssetConfigTxnWithSuggestedParams
- makeAssetDestroyTxnWithSuggestedParams
- makeAssetFreezeTxnWithSuggestedParams
- makeAssetTransferTxnWithSuggestedParams

To avoid this problem in the future, reKeyTo has been changed by rekeyTo in src/makeTxn.js and src/transaction.js (As it is in the node go-algorand)

2021-01-15 21:14 UTC, jasonpaulos requested changes
Thanks for noticing this inconsistency! I agree that `rekey` makes more sense than `reKey` does currently, but at the time rekeying was introduced to this package there wasn't yet a consensus on this. Unfortunately to avoid introducing a breaking change I think we need to make sure the `reKeyTo` property still works in the `Transaction` class. In v2 of this library we'd definitely want to use `rekey` though.

So I think there are two options here:
1. Make all makeTxn calls pass `reKey` to the Transaction constructors and leave Transaction alone.
2. Make all makeTxn calls pass `rekey` to the Transaction constructor, modify the Transaction class to use `rekey` internally, and put in a setter and getter for `reKey` (the old spelling) to avoid breaking existing user code.

If you have another idea of how to avoid a breaking change, let me know. Otherwise one of the above changes would have to be made before I can approve this.

2021-01-15 23:43 UTC, Alex99y commented
Perfect. I chose the first option, we make it less confusing. I agree to use the rekey for the next version.

2021-01-15 23:51 UTC, Alex99y commented
@jasonpaulos some tests are using _rekeyTo_, tomorrow I can take a look at all failed tests.

2021-01-18 15:00 UTC, jasonpaulos approved these changes
Everything looks good, thanks @Alex99y!

2021-01-18 15:01 UTC, merged