decodeAddress now verifies the checksum (fixes #262)
algorand/js-algorand-sdk pull request #269
Opened 2021-01-21 03:24 UTC by Neurone

Fixed also an npm command in readme

2021-01-21 03:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/algorand/js-algorand-sdk?pullRequest=269) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/algorand/js-algorand-sdk?pullRequest=269) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/algorand/js-algorand-sdk?pullRequest=269) it.</sub>

2021-01-21 18:08 UTC, jasonpaulos requested changes
Thanks for implementing this @Neurone, this looks great! Could you add a test in `tests/3.Address.js` to verify `decodeAddress` throws an error when given an address with an invalid checksum (probably with `assert.throws(...)`)? I'd be happy to accept once that's added.

2021-01-21 23:17 UTC, Neurone commented
Hi @jasonpaulos, sure. I'll send an update during this weekend.

2021-01-25 16:41 UTC, jasonpaulos approved these changes
Looks great! Thanks for working on this.

2021-01-25 16:42 UTC, merged