Begin migration to TypeScript
algorand/js-algorand-sdk pull request #302
Opened 2021-03-17 15:15 UTC by jdtzmn

This PR incorporates TypeScript compilation into the build steps, and migrates the following files and directories to TypeScript:
- [x] `src/transaction.js`
- [x] `src/makeTxn.js`
- [x] `src/encoding`
- [x] `src/nacl/naclWrapper.js`

Closes #295.

2021-03-18 21:19 UTC, jasonpaulos requested changes
Great work, I'm excited for this! I left a bunch of comments but I didn't see any major issues.

2021-03-18 21:19 UTC, jasonpaulos commented on src/types/transactions/base.ts
> +export enum TransactionType {
I really like this enum

2021-03-18 21:19 UTC, jasonpaulos commented on src/utils/utils.ts
> -function parseJSON(str, options = undefined) {
Nit: can you remove the type annotations in this function's docstring?

2021-03-18 21:19 UTC, jasonpaulos commented on examples/typescript_example.ts
> +  console.log(algosdk.decodeObj(signedTxn));
Nit: can you use `algosdk.decodeSignedTransaction` here instead?

2021-03-19 14:22 UTC, jdtzmn commented on src/encoding/address.ts
> +export function encodeAddress(address: Uint8Array | number[]) {
No real reason – I looked at what type the `nacl` library wanted for the `genericHash` function, and came up with a reasonable guess at what types we would want to use internally. If the `encodeAddress` will only ever accept `Uint8Array`s, then I can change it.

2021-03-19 14:49 UTC, jdtzmn commented on src/encoding/uint64.ts
> +export function decodeUint64(
Great suggestion! I've added it.

2021-03-19 14:51 UTC, jdtzmn commented on src/transaction.ts
> +    const transaction: AnyTransaction = { ...transactionObj };
Very smart.

2021-03-19 17:51 UTC, jdtzmn commented on src/makeTxn.ts
> -  rekeyTo = undefined
I (wrongly) assumed that optional types would become optional parameters. I've updated the parameters to be optional.

2021-03-19 18:57 UTC, jasonpaulos commented on src/encoding/address.ts
> +export function encodeAddress(address: Uint8Array | number[]) {
Yeah let's change this to `Uint8Array`

2021-03-19 18:57 UTC, jasonpaulos commented on src/transaction.ts
> +  group: undefined;
Sorry I wasn't specific. I think you should make it `group?: Buffer` here and on `TransactionStorageStructure`. Let me know if that doesn't make sense.

2021-03-19 19:21 UTC, jdtzmn commented on src/transaction.ts
> +  group: undefined;
Ah I see. Fixed!

2021-03-19 20:00 UTC, jasonpaulos approved these changes
Looks good!

2021-03-19 20:54 UTC, merged