Unlimited Assets
algorand/js-algorand-sdk pull request #527
Opened 2022-02-24 18:35 UTC by nicholasguoalgorand

Add endpoints related to the unlimited assets changes.
Tests TODO

2022-03-07 21:00 UTC, winder commented on src/client/v2/algod/accountInformation.ts
> +  excludeInfo(exclude: string) {
Should this be an array, or maybe mention in the documentation that something like `created-asset,created-apps` is a valid input?

2022-03-07 21:30 UTC, winder requested changes
It looks like, at least, the round param has not been removed from the balances endpoint.

Have the model objects been generated? I don't see the creator field removed either.

2022-03-07 21:32 UTC, winder commented
The new tests need to be enabled: `@unit.responses.unlimited_assets,@unit.indexer.ledger_refactoring,@unit.algod.ledger_refactoring`

2022-03-11 21:52 UTC, nicholasguoalgorand commented
> It looks like, at least, the round param has not been removed from the balances endpoint.
> 
> Have the model objects been generated? I don't see the creator field removed either.

How do I generate the model?

2022-03-17 18:37 UTC, winder commented on src/client/v2/algod/models/types.ts
> +  public data?: Record<string, any>;
Did you update the generator to support this change?

2022-03-17 18:41 UTC, winder reviewed
One question. Changes look good, but the tests aren't passing.

2022-03-17 19:09 UTC, winder commented
@algochoi do you know anything about the [build_and_test_chrome](https://circleci.com/gh/algorand/js-algorand-sdk/531?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) test? It seems to be flaky recently and we're not sure whats causing it.

2022-03-17 19:11 UTC, algochoi commented
@winder At first glance, it looks like there is some version mismatch between our chromedriver versions:

```
SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 97
```

I can take a closer look later today as well...

2022-03-17 21:14 UTC, winder approved these changes

2022-03-17 21:15 UTC, merged